#![no_std]

use core::alloc::{GlobalAlloc, Layout};
use core::ptr::NonNull;

// Include FFI bindings generated by bindgen via Meson
include!("bindings.rs");

/// Error type for memory allocation failures
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AllocError;

/// Allocate memory from the kernel heap
///
/// # Safety
/// The returned pointer must be deallocated with `dealloc()` when no longer needed.
///
/// # Arguments
/// * `size` - The number of bytes to allocate
///
/// # Returns
/// * `Ok(NonNull<u8>)` - Pointer to allocated memory
/// * `Err(AllocError)` - Allocation failed (out of memory)
///
/// # Example
/// ```no_run
/// use bindings_mm::{alloc, dealloc};
///
/// unsafe {
///     let ptr = alloc(1024).expect("allocation failed");
///     // Use the memory...
///     dealloc(ptr, 1024);
/// }
/// ```
pub unsafe fn alloc(size: usize) -> Result<NonNull<u8>, AllocError> {
    let ptr = mm_alloc(size);
    NonNull::new(ptr as *mut u8).ok_or(AllocError)
}

/// Deallocate memory previously allocated with `alloc()`
///
/// # Safety
/// * `ptr` must have been allocated by `alloc()` with the same `size`
/// * `ptr` must not be used after this call
/// * `ptr` must not be freed twice
///
/// # Arguments
/// * `ptr` - Pointer to memory to free
/// * `size` - Size of the allocation (currently unused, but kept for API consistency)
pub unsafe fn dealloc(ptr: NonNull<u8>, _size: usize) {
    mm_free(ptr.as_ptr() as *mut core::ffi::c_void);
}

/// Allocate memory with a specific layout
///
/// # Safety
/// The returned pointer must be deallocated with `dealloc_layout()` when no longer needed.
///
/// # Arguments
/// * `layout` - Memory layout describing size and alignment requirements
///
/// # Returns
/// * `Ok(NonNull<u8>)` - Pointer to allocated memory
/// * `Err(AllocError)` - Allocation failed
///
/// # Note
/// The current kernel allocator (`mm_alloc`) always returns page-aligned memory,
/// so alignment requirements <= PAGE_SIZE are automatically satisfied.
pub unsafe fn alloc_layout(layout: Layout) -> Result<NonNull<u8>, AllocError> {
    // Current mm_alloc returns page-aligned memory (4096 bytes)
    // For now, we ignore alignment requirements assuming PAGE_SIZE alignment
    // TODO: Add alignment checking if needed
    alloc(layout.size())
}

/// Deallocate memory with a specific layout
///
/// # Safety
/// * `ptr` must have been allocated by `alloc_layout()` with the same `layout`
/// * `ptr` must not be used after this call
/// * `ptr` must not be freed twice
pub unsafe fn dealloc_layout(ptr: NonNull<u8>, layout: Layout) {
    dealloc(ptr, layout.size());
}

/// Global allocator implementation for the kernel heap
///
/// This allows using Rust's allocation APIs like `Box`, `Vec`, `String` etc.
/// in `no_std` environments by implementing the `GlobalAlloc` trait.
///
/// # Example
/// ```no_run
/// #![no_std]
/// #![feature(default_alloc_error_handler)]
///
/// extern crate alloc;
///
/// use bindings_mm::KernelAllocator;
///
/// #[global_allocator]
/// static ALLOCATOR: KernelAllocator = KernelAllocator;
/// ```
pub struct KernelAllocator;

unsafe impl GlobalAlloc for KernelAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        match alloc_layout(layout) {
            Ok(ptr) => ptr.as_ptr(),
            Err(_) => core::ptr::null_mut(),
        }
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        if let Some(ptr) = NonNull::new(ptr) {
            dealloc_layout(ptr, layout);
        }
    }
}

/// Allocate zeroed memory from the kernel heap
///
/// # Safety
/// The returned pointer must be deallocated with `dealloc()` when no longer needed.
///
/// # Arguments
/// * `size` - The number of bytes to allocate
///
/// # Returns
/// * `Ok(NonNull<u8>)` - Pointer to zeroed memory
/// * `Err(AllocError)` - Allocation failed
pub unsafe fn alloc_zeroed(size: usize) -> Result<NonNull<u8>, AllocError> {
    let ptr = alloc(size)?;
    core::ptr::write_bytes(ptr.as_ptr(), 0, size);
    Ok(ptr)
}

/// Helper function to allocate memory for a specific type
///
/// # Safety
/// The returned pointer must be deallocated with `dealloc_typed()` when no longer needed.
///
/// # Returns
/// * `Ok(NonNull<T>)` - Pointer to uninitialized memory for type T
/// * `Err(AllocError)` - Allocation failed
///
/// # Example
/// ```no_run
/// use bindings_mm::{alloc_typed, dealloc_typed};
///
/// struct MyStruct {
///     value: u32,
/// }
///
/// unsafe {
///     let ptr = alloc_typed::<MyStruct>().expect("allocation failed");
///     ptr.as_ptr().write(MyStruct { value: 42 });
///     // Use the value...
///     core::ptr::drop_in_place(ptr.as_ptr());
///     dealloc_typed(ptr);
/// }
/// ```
pub unsafe fn alloc_typed<T>() -> Result<NonNull<T>, AllocError> {
    let layout = Layout::new::<T>();
    let ptr = alloc_layout(layout)?;
    Ok(NonNull::new_unchecked(ptr.as_ptr() as *mut T))
}

/// Deallocate memory for a specific type
///
/// # Safety
/// * `ptr` must have been allocated by `alloc_typed::<T>()`
/// * `ptr` must not be used after this call
/// * `ptr` must not be freed twice
/// * The value at `ptr` must have been dropped already (if needed)
pub unsafe fn dealloc_typed<T>(ptr: NonNull<T>) {
    let layout = Layout::new::<T>();
    dealloc_layout(NonNull::new_unchecked(ptr.as_ptr() as *mut u8), layout);
}
