
srcs += files('acpi.c')
srcs += files('mcfg.c')
srcs += files('madt.c')
srcs += files('hpet.c')

#madt_rssrc = [files('madt.rs')]

#libs += static_library(
#  'madt',
#  sources : madt_rssrc,
#  rust_abi: 'c',
#  rust_args: ['-C', 'panic=abort'],
#  link_with: [print_rs, runtime_rs],
#)
#
#rs_hdr += [['hm/madt.h', madt_rssrc]]
