#![no_std]

// Include FFI bindings generated by bindgen via Meson
include!("bindings.rs");

// net_if helper functions for safe Rust wrappers around C FFI
// Provides safe abstractions over raw pointers

/// Safe wrapper around netif_tx_packet
///
/// # Arguments
/// * `nif` - Network interface (reference)
/// * `dst` - Destination MAC address
/// * `mac_type` - EtherType (e.g., 0x0806 = ARP)
/// * `payload` - Payload data
///
/// # Returns
/// 0 on success, negative value on failure
pub fn tx_packet(nif: &net_if, dst: &[u8; 6], mac_type: u16, payload: &[u8]) -> i32 {
    unsafe {
        netif_tx_packet(
            nif as *const net_if as *mut net_if, // &net_if → *mut net_if
            dst.as_ptr() as *mut u8,             // &[u8; 6] → *mut u8
            mac_type,
            payload.as_ptr() as *mut u8,         // &[u8] → *mut u8
            payload.len(),
        )
    }
}

/// Helper for sending ARP packets
pub fn tx_arp_packet(nif: &net_if, dst: &[u8; 6], payload: &[u8]) -> i32 {
    tx_packet(nif, dst, 0x0608, payload) // 0x0806 = ARP (big endian)
}

/// Helper for sending IPv4 packets
pub fn tx_ipv4_packet(nif: &net_if, dst: &[u8; 6], payload: &[u8]) -> i32 {
    tx_packet(nif, dst, 0x0008, payload) // 0x0800 = IPv4 (big endian)
}

/// Safe wrapper around packet_buf_alloc
///
/// Allocates a packet buffer from the kernel's memory allocator.
///
/// # Arguments
/// * `size` - Size of the buffer to allocate in bytes
///
/// # Returns
/// * `Ok(&'static mut packet_t)` - Mutable reference to allocated packet on success
/// * `Err(i32)` - Error code on failure (-1)
///
/// # Safety
/// Returns a 'static lifetime because the kernel allocator does not support freeing.
/// The allocated packet lives for the entire program lifetime.
///
/// # Example
/// ```no_run
/// match alloc_packet_buf(1500) {
///     Ok(pkt) => {
///         let buf = unsafe { core::slice::from_raw_parts_mut(pkt.buf, pkt.buf_size) };
///         // Use the buffer...
///     }
///     Err(e) => {
///         // Handle allocation failure
///     }
/// }
/// ```
pub fn alloc_packet_buf(size: usize) -> Result<&'static mut packet_t, i32> {
    let mut pkt: *mut packet_t = core::ptr::null_mut();

    let ret = unsafe {
        packet_buf_alloc(size, &mut pkt as *mut *mut packet_t)
    };

    if ret == 0 && !pkt.is_null() {
        Ok(unsafe { &mut *pkt })
    } else {
        Err(ret)
    }
}
