#![no_std]

extern crate mm;

use core::ptr::NonNull;

// Include FFI bindings generated by bindgen via Meson
include!("bindings.rs");

// net_if helper functions for safe Rust wrappers around C FFI
// Provides safe abstractions over raw pointers

/// Safe wrapper around netif_tx_packet
///
/// # Arguments
/// * `nif` - Network interface (reference)
/// * `pkt` - Packet to transmit (reference to packet_t)
///
/// # Returns
/// 0 on success, negative value on failure
pub fn tx_packet(nif: &net_if, pkt: &packet_t) -> i32 {
    unsafe {
        netif_tx_packet(
            nif as *const net_if as *mut net_if,     // &net_if → *mut net_if
            pkt as *const packet_t as *mut packet_t, // &packet_t → *mut packet_t
        )
    }
}

/// Initialize packet offset fields based on network interface configuration
///
/// # Arguments
/// * `nif` - Network interface (reference)
/// * `pkt` - Packet to initialize (mutable reference to packet_t)
///
/// # Returns
/// 0 on success, negative value on failure
pub fn init_packet_offset(nif: &net_if, pkt: &mut packet_t) -> i32 {
    unsafe { netif_init_packet_offset(nif as *const net_if as *mut net_if, pkt as *mut packet_t) }
}

/// Get the transport layer offset for a network interface
///
/// # Arguments
/// * `nif` - Network interface (reference)
///
/// # Returns
/// Transport layer offset in bytes
pub fn transport_offset(nif: &net_if) -> u16 {
    unsafe { netif_trasport_offset(nif as *const net_if as *mut net_if) }
}

///// Helper for sending ARP packets (constructs Ethernet frame + ARP payload)
/////
///// # Arguments
///// * `nif` - Network interface
///// * `dst` - Destination MAC address
///// * `payload` - ARP payload (typically 28 bytes)
/////
///// # Returns
///// 0 on success, negative value on failure
//pub fn tx_arp_packet(nif: &net_if, dst: &[u8; 6], payload: &[u8]) -> i32 {
//    unsafe {
//        // Allocate packet buffer for Ethernet header (14 bytes) + ARP payload
//        let total_size = 14 + payload.len();
//        let Ok(pkt) = alloc_packet_buf(nif, total_size) else {
//            return -1;
//        };
//
//        // Get buffer slice
//        let buf = core::slice::from_raw_parts_mut(pkt.buf, pkt.buf_size);
//
//        // Construct Ethernet header
//        // Destination MAC (6 bytes)
//        buf[0..6].copy_from_slice(dst);
//        // Source MAC (6 bytes)
//        buf[6..12].copy_from_slice(&nif.mac_addr);
//        // EtherType: ARP = 0x0806 (big endian)
//        buf[12..14].copy_from_slice(&[0x08, 0x06]);
//
//        // Copy ARP payload
//        buf[14..14 + payload.len()].copy_from_slice(payload);
//
//        // Send packet
//        let ret = tx_packet(nif, pkt);
//
//        // Free packet
//        PacketBuf::free_leaked(pkt);
//
//        ret
//    }
//}

// /// Helper for sending IPv4 packets (constructs Ethernet frame + payload)
// ///
// /// # Arguments
// /// * `nif` - Network interface
// /// * `dst` - Destination MAC address
// /// * `payload` - IPv4 payload (IP header + data)
// ///
// /// # Returns
// /// 0 on success, negative value on failure
// pub fn tx_ipv4_packet(nif: &net_if, dst: &[u8; 6], payload: &[u8]) -> i32 {
//     unsafe {
//         // Allocate packet buffer for Ethernet header (14 bytes) + IPv4 payload
//         let total_size = 14 + payload.len();
//         let Ok(pkt) = alloc_packet_buf(nif, total_size) else {
//             return -1;
//         };
//
//         // Get buffer slice
//         let buf = core::slice::from_raw_parts_mut(pkt.buf, pkt.buf_size);
//
//         // Construct Ethernet header
//         // Destination MAC (6 bytes)
//         buf[0..6].copy_from_slice(dst);
//         // Source MAC (6 bytes)
//         buf[6..12].copy_from_slice(&nif.mac_addr);
//         // EtherType: IPv4 = 0x0800 (big endian)
//         buf[12..14].copy_from_slice(&[0x08, 0x00]);
//
//         // Copy IPv4 payload
//         buf[14..14 + payload.len()].copy_from_slice(payload);
//
//         // Send packet
//         let ret = tx_packet(nif, pkt);
//
//         // Free packet
//         PacketBuf::free_leaked(pkt);
//
//         ret
//     }
// }

/// Error type for packet buffer allocation
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PacketAllocError;

/// Owned packet buffer with automatic memory management
///
/// This struct owns both the packet_t structure and its buffer.
/// When dropped, it automatically frees the allocated memory.
///
/// # Example
/// ```no_run
/// use bindings_net::PacketBuf;
///
/// let mut pkt = PacketBuf::new(1500).expect("allocation failed");
/// let buf = pkt.buf_mut();
/// buf[0] = 0x42;
/// // Packet is automatically freed when pkt goes out of scope
/// ```
pub struct PacketBuf {
    pkt: NonNull<packet_t>,
    buf: NonNull<u8>,
    size: usize,
}

impl PacketBuf {
    /// Allocate a new packet buffer using C packet_buf_alloc
    ///
    /// # Arguments
    /// * `nif` - Network interface to allocate packet for
    /// * `size` - Size of the buffer in bytes
    ///
    /// # Returns
    /// * `Ok(PacketBuf)` - Owned packet buffer
    /// * `Err(PacketAllocError)` - Allocation failed
    pub fn new(nif: &net_if, size: usize) -> Result<Self, PacketAllocError> {
        unsafe {
            let mut pkt_ptr: *mut packet_t = core::ptr::null_mut();

            // Call C function packet_buf_alloc
            // Note: bindgen couldn't resolve net_if type, so we cast to *mut [u8; 0]
            let ret = packet_buf_alloc(
                nif as *const net_if as *mut [u8; 0],
                size,
                &mut pkt_ptr as *mut *mut packet_t,
            );

            if ret != 0 || pkt_ptr.is_null() {
                return Err(PacketAllocError);
            }

            let pkt = NonNull::new_unchecked(pkt_ptr);
            let buf = NonNull::new_unchecked((*pkt_ptr).buf);

            Ok(PacketBuf { pkt, buf, size })
        }
    }

    /// Get a reference to the packet_t struct
    pub fn packet(&self) -> &packet_t {
        unsafe { self.pkt.as_ref() }
    }

    /// Get a mutable reference to the packet_t struct
    pub fn packet_mut(&mut self) -> &mut packet_t {
        unsafe { self.pkt.as_mut() }
    }

    /// Get the buffer as a slice
    pub fn buf(&self) -> &[u8] {
        unsafe { core::slice::from_raw_parts(self.buf.as_ptr(), self.size) }
    }

    /// Get the buffer as a mutable slice
    pub fn buf_mut(&mut self) -> &mut [u8] {
        unsafe { core::slice::from_raw_parts_mut(self.buf.as_ptr(), self.size) }
    }

    /// Get the buffer size
    pub fn size(&self) -> usize {
        self.size
    }

    /// Get a raw pointer to the packet_t (for FFI)
    ///
    /// # Safety
    /// The pointer is valid as long as this PacketBuf exists
    pub fn as_ptr(&self) -> *const packet_t {
        self.pkt.as_ptr()
    }

    /// Get a mutable raw pointer to the packet_t (for FFI)
    ///
    /// # Safety
    /// The pointer is valid as long as this PacketBuf exists
    pub fn as_mut_ptr(&mut self) -> *mut packet_t {
        self.pkt.as_ptr()
    }

    /// Consume the PacketBuf and leak it, returning a 'static reference
    ///
    /// This is useful when you want to pass ownership to C code that
    /// doesn't support Rust's ownership model.
    ///
    /// # Safety
    /// The packet will NOT be automatically freed. You must manually call
    /// `free_leaked()` or use `mm_free()` directly to avoid memory leaks.
    pub fn leak(self) -> &'static mut packet_t {
        let ptr = self.pkt.as_ptr();
        core::mem::forget(self); // Don't run Drop
        unsafe { &mut *ptr }
    }

    /// Free a leaked packet
    ///
    /// # Safety
    /// * `pkt` must have been created by `PacketBuf::leak()`
    /// * `pkt` must not be used after this call
    /// * `pkt` must not be freed twice
    pub unsafe fn free_leaked(pkt: &'static mut packet_t) {
        // Use C function packet_buf_free to properly free the packet
        packet_buf_free(pkt as *mut packet_t);
    }
}

impl Drop for PacketBuf {
    fn drop(&mut self) {
        unsafe {
            // Use C function packet_buf_free to properly free the packet
            packet_buf_free(self.pkt.as_ptr());
        }
    }
}

/// Allocate a packet buffer (legacy API for compatibility)
///
/// # Deprecated
/// Use `PacketBuf::new()` instead for automatic memory management.
///
/// # Arguments
/// * `nif` - Network interface to allocate packet for
/// * `size` - Size of the buffer to allocate in bytes
///
/// # Returns
/// * `Ok(&'static mut packet_t)` - Mutable reference to allocated packet on success
/// * `Err(i32)` - Error code on failure (-1)
///
/// # Safety
/// Returns a 'static lifetime. The packet must be manually freed with
/// `PacketBuf::free_leaked()` to avoid memory leaks.
pub fn alloc_packet_buf(nif: &net_if, size: usize) -> Result<&'static mut packet_t, i32> {
    match PacketBuf::new(nif, size) {
        Ok(pkt) => Ok(pkt.leak()),
        Err(_) => Err(-1),
    }
}
