ENTRY(entry)

SECTIONS
{
    . = 0x100000;
    _kernel_start = .;

    .text :{
        _text_start = .;
        *(.entry);
        *(.text);
        _text_end = .;
    }
    .data :{    /* 有意値で初期化されるstatic変数 */
        _data_start = .;
        *(.data);
        _data_end = .;
    }
    .bss :{     /* ゼロで初期化されるstatic変数 */
        _bss_start = .;
        *(.bss);
        _bss_end = .;
    }

    . = ALIGN(32);
    stack = .;
    . += 4096;
    . += 1024;

    _kernel_end = .;
}
