
srcs += files('boot.s')
srcs += files('boot_ap.S')
srcs += files('main.c')
srcs += files('qemu-debugcon.c')
srcs += files('print.c')
srcs += files('string.c')
srcs += files('int.S')
srcs += files('int.c')
srcs += files('core.c')
srcs += files('cpuid.c')
srcs += files('device.c')
srcs += files('module.c')
srcs += files('pic.c')
srcs += files('pit.c')
srcs += files('virtio-net.c')
srcs += files('virtio.c')
srcs += files('packed_virtq.c')
srcs += files('exception.c')

subdir('mm')
subdir('acpi')
subdir('pci')
subdir('apic')
subdir('timer')
subdir('net')
