#ifndef _INCLUDED_VECTOR_H_
#define _INCLUDED_VECTOR_H_

#define DIVIDE_VECTOR 0
#define DEBUG_VECTOR 1
#define NMI_VECTOR 2
#define BRAKEPOINT_VECTOR 3
#define OVERFLOW_VECTOR 4
#define BR_BOUND_VECTOR 5
#define INVALID_OP_VECTOR 6
#define DEVICE_NOT_VECTOR 7
#define DOUBLE_FAULT 8
#define COPROC_SEGMENT_VECTOR 9
#define INVALID_TSS_VECTOR 10
#define SEG_NOT_VECTOR 11
#define STACK_EXCEPTION_VECTOR 12
#define GENERAL_PROTECTION_VECTOR 13
#define PAGE_FAULT_VECTOR 14
#define COPROC_ERROR_VECOTR 16
#define ALIGNMENT_CHECK_VECTOR 17
#define MACHINE_CHECK_VECTOR 18
#define SIMD_EXCEPTION_VECTOR 19

#define SYSTEM_CALL_VECTOR 128

#define PIC_MASTER_CMD_STATE_PORT 0x20
#define PIC_MASTER_DATA_PORT 0x21
#define PIC_SLAVE_CMD_STATE_PORT 0xA0
#define PIC_SLAVE_DATA_PORT 0xA1

#define PIC_MASTER_ICW1 0x11
#define PIC_MASTER_ICW2 0x20 // use after 0x20 number interrupt descriptor table
#define PIC_MASTER_ICW3 0x04
// #define PIC_MASTER_ICW4 0x01
#define PIC_MASTER_ICW4 0x00

#define PIC_SLAVE_ICW1 PIC_MASTER_ICW1
#define PIC_SLAVE_ICW2 0x28
#define PIC_SLAVE_ICW3 0x02
#define PIC_SLAVE_ICW4 PIC_MASTER_ICW4

#define PIC_IMR_MASK_IRQ0 0x01
#define PIC_IMR_MASK_IRQ1 0x02
#define PIC_IMR_MASK_IRQ2 0x04
#define PIC_IMR_MASK_IRQ3 0x08
#define PIC_IMR_MASK_IRQ4 0x10
#define PIC_IMR_MASK_IRQ5 0x20
#define PIC_IMR_MASK_IRQ6 0x40
#define PIC_IMR_MASK_IRQ7 0x80
#define PIC_IMR_MASK_IRQ_ALL 0xff

#define PIC_OCW2_EOI 0x20

#endif
