#pragma once

#define EXC_NUM_DIVIDE_ERROR 0
#define EXC_NUM_DEBUG 1
#define EXC_NUM_NMI 2
#define EXC_NUM_BREAKPOINT 3
#define EXC_NUM_OVERFLOW 4
#define EXC_NUM_BOUND_RANGE_EXCEEDED 5
#define EXC_NUM_INVALID_OPCODE 6
#define EXC_NUM_DEVICE_NOT_AVAIL 7
#define EXC_NUM_DOUBLE_FAULT 8
#define EXC_NUM_COPROC_SEGMENT_OVERRUN 9
#define EXC_NUM_INVALID_TSS 10
#define EXC_NUM_SEGMENT_NOT_PRESENT 11
#define EXC_NUM_STACK_FAULT 12
#define EXC_NUM_GENERAL_PROTECTION 13
#define EXC_NUM_PAGE_FAULT 14
#define EXC_NUM_FPU_ERROR 16
#define EXC_NUM_ALIGN_CHECK 17
#define EXC_NUM_MACHINE_CHECK 18
#define EXC_NUM_SIMD_FP 19
#define EXC_NUM_VIRT 20
#define EXC_NUM_CONTROL_PROTECT 21

#define IRQ_NUM_TIMER 32
#define IRQ_VIRTIO_NET_RX 33
#define IRQ_VIRTIO_NET_TX 34
