// lib.rs for print_rs crate

// Include FFI bindings generated by bindgen
include!("bindings.rs");

// kprintf! macro for convenient C printf calls
#[macro_export]
macro_rules! kprintf {
    ($fmt:expr) => {
        unsafe {
            $crate::kprintf(concat!($fmt, "\0").as_ptr() as *const ::std::os::raw::c_char);
        }
    };
}
