#![no_std]

use core::fmt;

// Include FFI bindings generated by bindgen
include!("bindings.rs");

/// Zero-sized writer that outputs to the C puts function
#[doc(hidden)]
pub struct KPrintWriter;

impl fmt::Write for KPrintWriter {
    fn write_str(&mut self, s: &str) -> fmt::Result {
        // Call C putsn function directly with pointer and length
        // No buffer copy needed!
        unsafe {
            putsn(
                s.as_ptr() as *const core::ffi::c_char,
                s.len() as core::ffi::c_ulong,
            );
        }

        Ok(())
    }
}

/// Print formatted text to kernel output
#[macro_export]
macro_rules! kprint {
    ($($arg:tt)*) => {{
        use core::fmt::Write;
        let _ = write!($crate::KPrintWriter, $($arg)*);
    }};
}

/// Print formatted text with newline to kernel output
#[macro_export]
macro_rules! kprintln {
    () => { $crate::kprint!("\n") };
    ($($arg:tt)*) => {{
        use core::fmt::Write;
        let _ = writeln!($crate::KPrintWriter, $($arg)*);
    }};
}
